display:
  background_image: ((background_image))
resource_types:

- name: terraform
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.14.4
- name: pool
  type: registry-image
  source:
    # pool is included by default but the bundled resource is broke
    # https://github.com/concourse/pool-resource/pull/56
    repository: concourse/pool-resource
    tag: 1.1.3

resources:

- name: tech-ops-private
  icon: github
  type: git
  source:
    branch: ((deployment_branch_tech_ops_private))
    uri: git@github.com:alphagov/tech-ops-private.git
    private_key: ((re-autom8-ci-github-ssh-private-key))
    paths:
      - reliability-engineering/terraform/deployments/((deployment_account_name))/((deployment_name))
      - reliability-engineering/terraform/deployments/((deployment_account_name))/cd-main
      - reliability-engineering/terraform/modules/gds-ips
- name: tech-ops
  icon: github
  type: git
  source:
    branch: ((deployment_branch_tech_ops))
    tag_filter: ((deployment_tag))
    uri: git@github.com:alphagov/tech-ops.git
    private_key: ((re-autom8-ci-github-ssh-private-key))
    paths:
      - reliability-engineering/terraform/modules
      - reliability-engineering/pipelines/tasks/asg-scale-capacity.yml
      - reliability-engineering/pipelines/tasks/concourse-get-workers.yml
      - reliability-engineering/pipelines/tasks/concourse-land-workers.yml
      - reliability-engineering/pipelines/tasks/concourse-provider-config.yml
      - reliability-engineering/pipelines/tasks/generate-deploy-info-pipelines-pipeline.yml
      - reliability-engineering/pipelines/tasks/generate-roll-instances-pipeline.yml
      - reliability-engineering/pipelines/tasks/sign-tag.yml
      - reliability-engineering/pipelines/tasks/verify-tag.yml
      - reliability-engineering/pipelines/concourse-deployer.yml
      - reliability-engineering/dockerfiles/test.Dockerfile
- name: infra
  icon: terraform
  type: terraform
  source:
    env_name: default
    backend_type: s3
    private_key: ((re-autom8-ci-github-ssh-private-key))
    backend_config:
      bucket: ((statefile_bucket))
      region: ((statefile_region))
      key: ((deployment_name)).tfstate
- name: version
  type: semver
  source:
    driver: s3
    access_key_id: ((readonly_access_key_id))
    secret_access_key: ((readonly_secret_access_key))
    session_token: ((readonly_session_token))
    bucket: ((readonly_private_bucket_name))
    key: ((deployment_name))-version
    region_name: eu-west-2
    initial_version: '1.0.0'
- name: ecr
  type: docker-image
  icon: layers
  source:
    repository: ((readonly_private_ecr_repo_url))
- name: pool-repo
  type: git
  icon: github
  source:
    branch: pool
    uri: ((readonly_codecommit_pool_uri))
    private_key: ((readonly_codecommit_private_key))
- name: pool
  type: pool
  icon: pool
  source:
    branch: pool
    uri: ((readonly_codecommit_pool_uri))
    private_key: ((readonly_codecommit_private_key))
    pool: my-pool
- name: a-test-lock-config
  type: mock
  source:
    create_files:
      name: a-test-lock
      metadata: ''
- name: concourse-release
  type: github-release
  check_every: 30m
  source:
    owner: concourse
    repository: concourse

jobs:

- name: update
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops-private
      trigger: true
    - get: tech-ops
      trigger: true
    - get: infra
  - task: verify-tech-ops-tag
    file: tech-ops/reliability-engineering/pipelines/tasks/verify-tag.yml
    input_mapping:
      repository: tech-ops
    params:
      GPG_VERIFICATION_KEY: ((re-autom8-ci-github-gpg-private-key))
      GPG_VERIFICATION_TAG: ((deployment_tag))
  - set_pipeline: deploy
    file: tech-ops/reliability-engineering/pipelines/concourse-deployer.yml
    vars:
      deployment_name: ((deployment_name))
      deployment_account_name: ((deployment_account_name))
      deployment_subdomain: ((deployment_subdomain))
      deployment_branch_tech_ops: ((deployment_branch_tech_ops))
      deployment_branch_tech_ops_private: ((deployment_branch_tech_ops_private))
      statefile_region: ((statefile_region))
      deployment_tag: ((deployment_tag))
      background_image: ((background_image))
      statefile_bucket: ((statefile_bucket))

- name: deploy
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops-private
      passed: [update]
      trigger: true
    - get: tech-ops
      passed: [update]
      trigger: true
    - get: infra
      passed: [update]
    - get: concourse-release
      trigger: true
      params:
        globs:
        - concourse-*-linux-amd64.tgz.sha1
  - task: configure-providers
    file: tech-ops/reliability-engineering/pipelines/tasks/concourse-provider-config.yml
    params:
      DEPLOYMENT_NAME: ((deployment_name))
      DEPLOYMENT_SUBDOMAIN: ((deployment_subdomain))
  - put: infra
    params:
      terraform_source: tech-ops-private/reliability-engineering/terraform/deployments/((deployment_account_name))/((deployment_name))
      override_files:
      - concourse-provider-config/provider_concourse_override.tf.json
      var_files:
      - concourse-provider-config/version.tfvars

- name: scale-out
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops-private
      passed: [deploy]
      trigger: true
    - get: tech-ops
      passed: [deploy]
      trigger: true
    - get: infra
      passed: [deploy]
    - get: concourse-release
      passed: [deploy]
      trigger: true
      params:
        globs:
        - concourse-*-linux-amd64.tgz.sha1
  - task: configure-providers
    file: tech-ops/reliability-engineering/pipelines/tasks/concourse-provider-config.yml
    params:
      DEPLOYMENT_NAME: ((deployment_name))
      DEPLOYMENT_SUBDOMAIN: ((deployment_subdomain))
  - task: get-current-workers
    file: tech-ops/reliability-engineering/pipelines/tasks/concourse-get-workers.yml
    params:
      DEPLOYMENT_NAME: ((deployment_name))
      DEPLOYMENT_SUBDOMAIN: ((deployment_subdomain))
  - do:
    - in_parallel:
      - task: scale-out-web-node-asg
        file: tech-ops/reliability-engineering/pipelines/tasks/asg-scale-capacity.yml
        params:
          ASG_PREFIX: ((deployment_name))-concourse-web
          SCALE_DIRECTION: out
      - task: scale-out-main-team-workers-asg
        file: tech-ops/reliability-engineering/pipelines/tasks/asg-scale-capacity.yml
        params:
          ASG_PREFIX: ((deployment_name))-main-concourse-worker
          SCALE_DIRECTION: out
    - task: land-old-workers
      file: tech-ops/reliability-engineering/pipelines/tasks/concourse-land-workers.yml
      params:
        DEPLOYMENT_NAME: ((deployment_name))
        DEPLOYMENT_SUBDOMAIN: ((deployment_subdomain))
    on_failure:
      put: infra # try to scale back in on failure to stay in sync
      attempts: 10
      params:
        terraform_source: tech-ops-private/reliability-engineering/terraform/deployments/((deployment_account_name))/((deployment_name))
        override_files:
        - concourse-provider-config/provider_concourse_override.tf.json
        var_files:
        - concourse-provider-config/version.tfvars

- name: scale-in
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops-private
      passed: [scale-out]
      trigger: true
    - get: tech-ops
      passed: [scale-out]
      trigger: true
    - get: infra
      passed: [scale-out]
    - get: concourse-release
      passed: [scale-out]
      trigger: true
      params:
        globs:
        - concourse-*-linux-amd64.tgz.sha1
  - task: configure-providers
    file: tech-ops/reliability-engineering/pipelines/tasks/concourse-provider-config.yml
    params:
      DEPLOYMENT_NAME: ((deployment_name))
      DEPLOYMENT_SUBDOMAIN: ((deployment_subdomain))
  - put: infra
    attempts: 10
    params:
      terraform_source: tech-ops-private/reliability-engineering/terraform/deployments/((deployment_account_name))/((deployment_name))
      override_files:
      - concourse-provider-config/provider_concourse_override.tf.json
      var_files:
      - concourse-provider-config/version.tfvars

- name: generate-roll-team-workers
  serial: true
  plan:
  - get: tech-ops
    attempts: 10
    passed: [scale-in]
    trigger: true
  - task: generate-roll-instances-pipeline
    file: tech-ops/reliability-engineering/pipelines/tasks/generate-roll-instances-pipeline.yml
    params:
      DEPLOYMENT_NAME: ((deployment_name))
      DEPLOYMENT_SUBDOMAIN: ((deployment_subdomain))
      FLY_USERNAME: main
      FLY_PASSWORD: ((readonly_local_user_password))
  - set_pipeline: roll-instances
    file: roll-instances-pipeline/roll-instances.json
    vars:
      deployment_subdomain: ((deployment_subdomain))
      deployment_branch: ((deployment_branch))
      deployment_tag: ((deployment_tag))
      deployment_name: ((deployment_name))

- name: configure-info-pipeline
  serial: true
  plan:
  - in_parallel:
    - get: tech-ops-private
      attempts: 10
      passed: [scale-in]
      trigger: true
    - get: tech-ops
      attempts: 10
      passed: [scale-in]
      trigger: true
  - task: generate-deploy-info-pipelines-pipeline
    file: tech-ops/reliability-engineering/pipelines/tasks/generate-deploy-info-pipelines-pipeline.yml
    params:
      DEPLOYMENT_NAME: ((deployment_name))
      DEPLOYMENT_SUBDOMAIN: ((deployment_subdomain))
      FLY_USERNAME: main
      FLY_PASSWORD: ((readonly_local_user_password))
  - set_pipeline: deploy-info-pipelines
    file: deploy-info-pipelines-pipeline/deploy-info-pipelines.json
    vars:
      deployment_branch: ((deployment_branch))

- name: test
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops-private
      attempts: 10
      passed: [scale-in]
      trigger: true
    - get: tech-ops
      attempts: 10
      passed: [scale-in]
      trigger: true
    - get: version
      attempts: 10
      params: {bump: minor}
    - get: concourse-release
      passed: [scale-in]
      trigger: true

  # this is a simple check to ensure push to ecr works
  - put: ecr
    attempts: 10
    params:
      build: version
      dockerfile: tech-ops/reliability-engineering/dockerfiles/test.Dockerfile
      tag: version/version
      tag_prefix: ((deployment_name))-

  # the following tasks exercise the codecommit repo provided for pool-resource
  - task: init-pool
    attempts: 10
    file: tech-ops/reliability-engineering/pipelines/tasks/test-init-pool.yml
    output_mapping:
      repo: pool
  - put: pool-repo
    attempts: 10
    params:
      repository: pool
      force: true
  - get: a-test-lock-config  # defines a lock
    attempts: 10
  - put: add-lock  # adds the lock to the pool
    attempts: 10
    resource: pool
    params:
      add: a-test-lock-config
  - put: acquire-lock  # get the lock
    attempts: 10
    resource: pool
    params:
      acquire: true
  - put: release-lock  # releases the lock
    attempts: 10
    resource: pool
    params:
      release: a-test-lock-config

  # check that logs are arriving in CloudWatch
  - in_parallel:
    - task: check-web-logs
      attempts: 10
      file: tech-ops/reliability-engineering/pipelines/tasks/test-log-shipping.yml
      timeout: 10m
      params:
        LOG_GROUP: /((deployment_name))/concourse/web
    - task: check-worker-logs
      attempts: 10
      file: tech-ops/reliability-engineering/pipelines/tasks/test-log-shipping.yml
      timeout: 10m
      params:
        LOG_GROUP: /((deployment_name))/concourse/worker

- name: tag-release
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops
      passed: [generate-roll-team-workers, configure-info-pipeline, test]
      trigger: true
    - get: concourse-release
      passed: [test]
      trigger: true
    - get: version
      params: {bump: minor}

  # this promotes the repo for use in other deployments (eg cd-staging -> cd)
  - task: tag-tech-ops
    file: tech-ops/reliability-engineering/pipelines/tasks/sign-tag.yml
    input_mapping:
      repository: tech-ops
      version: version
    params:
      SSH_PRIVATE_KEY: ((re-autom8-ci-github-ssh-private-key))
      GPG_PRIVATE_KEY: ((re-autom8-ci-github-gpg-private-key))
      TAG_PREFIX: ((deployment_name))-
  - put: version
    params:
      file: version/version
