
resource_types:

- name: terraform
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.12.25
- name: paas-semver
  type: docker-image
  source:
    repository: governmentpaas/semver-resource
    tag: latest

resources:

- name: tech-ops-private
  icon: github-circle
  type: git
  source:
    branch: ((deployment_branch))
    uri: git@github.com:alphagov/tech-ops-private.git
    private_key: ((re-autom8-ci-github-ssh-private-key))
    paths:
      - reliability-engineering/terraform/deployments/gds-tech-ops/((deployment_name))
- name: tech-ops
  icon: github-circle
  type: git
  source:
    branch: ((deployment_branch))
    tag_filter: ((deployment_tag))
    uri: git@github.com:alphagov/tech-ops.git
    private_key: ((re-autom8-ci-github-ssh-private-key))
    paths:
      - reliability-engineering/terraform/modules
      - reliability-engineering/pipelines/tasks/asg-scale-max-capacity.yml
      - reliability-engineering/pipelines/tasks/concourse-land-workers.yml
      - reliability-engineering/pipelines/tasks/concourse-provider-config.yml
      - reliability-engineering/pipelines/tasks/sign-tag.yml
      - reliability-engineering/pipelines/tasks/verify-tag.yml
      - reliability-engineering/pipelines/concourse-deployer.yml
      - reliability-engineering/dockerfiles/test.Dockerfile
- name: infra
  icon: terraform
  type: terraform
  source:
    env_name: default
    backend_type: s3
    private_key: ((re-autom8-ci-github-ssh-private-key))
    backend_config:
      bucket: gds-tech-ops-tfstate
      region: eu-west-2
      key: ((deployment_name)).tfstate
- name: version
  type: paas-semver
  source:
    driver: s3
    key: ((deployment_name))-version
    bucket: ((readonly_private_bucket_name))
    region_name: eu-west-2
    initial_version: '1.0.0'
- name: ecr
  type: docker-image
  icon: layers
  source:
    repository: ((readonly_private_ecr_repo_url))
- name: pool
  type: pool
  source:
    branch: pool
    uri: ((readonly_codecommit_pool_uri))
    private_key: ((readonly_codecommit_private_key))
- name: a-test-lock-config
  type: mock
  source:
    create_files:
      name: a-test-lock
      metadata: ''
- name: concourse-release
  type: github-release
  source:
    owner: concourse
    repository: concourse
- name: fly
  type: registry-image
  source:
    repository: concourse/concourse-pipeline-resource
    tag: latest

jobs:

- name: update
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops-private
      trigger: true
    - get: tech-ops
      trigger: true
    - get: infra
  - task: verify-tech-ops-tag
    file: tech-ops/reliability-engineering/pipelines/tasks/verify-tag.yml
    input_mapping:
      repository: tech-ops
    params:
      GPG_VERIFICATION_KEY: ((re-autom8-ci-github-gpg-private-key))
      GPG_VERIFICATION_TAG: ((deployment_tag))
  - set_pipeline: deploy
    file: tech-ops/reliability-engineering/pipelines/concourse-deployer.yml
    vars:
      deployment_name: ((deployment_name))
      deployment_branch: ((deployment_branch))
      deployment_tag: ((deployment_tag))

- name: deploy
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops-private
      passed: [update]
      trigger: true
    - get: tech-ops
      passed: [update]
      trigger: true
    - get: infra
      passed: [update]
    - get: concourse-release
      trigger: true
      params:
        globs:
        - concourse-*-linux-amd64.tgz.sha1
  - task: configure-providers
    file: tech-ops/reliability-engineering/pipelines/tasks/concourse-provider-config.yml
    params:
      DEPLOYMENT_NAME: ((deployment_name))
  - put: infra
    params:
      terraform_source: tech-ops-private/reliability-engineering/terraform/deployments/gds-tech-ops/((deployment_name))
      override_files:
      - concourse-provider-config/provider_concourse_override.tf.json
      var_files:
      - concourse-provider-config/version.tfvars
  - set_pipeline: roll-instances
    file: tech-ops-private/reliability-engineering/terraform/deployments/gds-tech-ops/((deployment_name))/roll-instances.yml
  - set_pipeline: deploy-info-pipelines
    file: tech-ops-private/reliability-engineering/terraform/deployments/gds-tech-ops/((deployment_name))/deploy-info-pipelines.yml
    vars:
      deployment_branch: ((deployment_branch))

- name: scale-out
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops-private
      passed: [deploy]
      trigger: true
    - get: tech-ops
      passed: [deploy]
      trigger: true
    - get: infra
      passed: [deploy]
    - get: concourse-release
      passed: [deploy]
      params:
        globs:
        - concourse-*-linux-amd64.tgz.sha1
    - get: fly
  - task: configure-providers
    file: tech-ops/reliability-engineering/pipelines/tasks/concourse-provider-config.yml
    params:
      DEPLOYMENT_NAME: ((deployment_name))
  - task: get-current-workers
    file: tech-ops/reliability-engineering/pipelines/tasks/concourse-get-workers.yml
    image: fly
    params:
      DEPLOYMENT_NAME: ((deployment_name))
  - do:
    - in_parallel:
      - task: scale-out-web-node-asg
        file: tech-ops/reliability-engineering/pipelines/tasks/asg-scale-max-capacity.yml
        params:
          ASG_PREFIX: ((deployment_name))-concourse-web
      - task: scale-out-main-team-workers-asg
        file: tech-ops/reliability-engineering/pipelines/tasks/asg-scale-max-capacity.yml
        params:
          ASG_PREFIX: ((deployment_name))-main-concourse-worker
    - task: land-old-workers
      file: tech-ops/reliability-engineering/pipelines/tasks/concourse-land-workers.yml
      image: fly
      params:
        DEPLOYMENT_NAME: ((deployment_name))
    on_failure:
      put: infra # try to scale back in on failure to stay in sync
      attempts: 10
      params:
        terraform_source: tech-ops-private/reliability-engineering/terraform/deployments/gds-tech-ops/((deployment_name))
        override_files:
        - concourse-provider-config/provider_concourse_override.tf.json
        var_files:
        - concourse-provider-config/version.tfvars

- name: scale-in
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops-private
      passed: [scale-out]
      trigger: true
    - get: tech-ops
      passed: [scale-out]
      trigger: true
    - get: infra
      passed: [scale-out]
    - get: concourse-release
      passed: [scale-out]
      params:
        globs:
        - concourse-*-linux-amd64.tgz.sha1
  - task: configure-providers
    file: tech-ops/reliability-engineering/pipelines/tasks/concourse-provider-config.yml
    params:
      DEPLOYMENT_NAME: ((deployment_name))
  - put: infra
    attempts: 10
    params:
      terraform_source: tech-ops-private/reliability-engineering/terraform/deployments/gds-tech-ops/((deployment_name))
      override_files:
      - concourse-provider-config/provider_concourse_override.tf.json
      var_files:
      - concourse-provider-config/version.tfvars

- name: test
  serial: true
  serial_groups: [deploy]
  plan:
  - in_parallel:
    - get: tech-ops-private
      attempts: 50
      passed: [scale-in]
      trigger: true
    - get: tech-ops
      attempts: 50
      passed: [scale-in]
      trigger: true
    - get: version
      attempts: 50
      params: {bump: minor}

  # this is a simple check to ensure push to ecr works
  - put: ecr
    params:
      build: version
      dockerfile: tech-ops/reliability-engineering/dockerfiles/test.Dockerfile
      tag: version/version
      tag_prefix: ((deployment_name))-

  # the following tasks exercise the codecommit repo provided for pool-resource
  - task: init-pool
    file: tech-ops/reliability-engineering/pipelines/tasks/test-init-pool.yml
    output_mapping:
      repo: pool
  - put: pool
    params:
      repository: pool
      force: true
  - get: a-test-lock-config  # defines a lock
  - put: pool  # adds the lock to the pool
    params:
      add: a-test-lock-config
  - put: pool  # claims the lock
    params:
      claim: pool
  - put: pool  # releases the lock
    params:
      release: pool

  # this promotes the repo for use in other deployments (eg cd-staging -> cd)
  - task: tag-tech-ops
    file: tech-ops/reliability-engineering/pipelines/tasks/sign-tag.yml
    input_mapping:
      repository: tech-ops
      version: version
    params:
      SSH_PRIVATE_KEY: ((re-autom8-ci-github-ssh-private-key))
      GPG_PRIVATE_KEY: ((re-autom8-ci-github-gpg-private-key))
      TAG_PREFIX: ((deployment_name))-
  - put: version
    params:
      file: version/version
