platform: linux
image_resource:
  type: registry-image
  source:
    repository: ghcr.io/alphagov/automate/task-toolbox
    tag: latest
inputs:
- name: infra # terraform metadata
- name: concourse-release
outputs:
- name: concourse-provider-config
params:
  DEPLOYMENT_NAME:
run:
  path: /bin/bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    echo "generating concourse provider config..."
    mkdir -p concourse-provider-config
    cat <<EOF > concourse-provider-config/provider_concourse_override.tf.json
    {
      "provider": {
        "concourse": {
          "target": "",
          "url": "https://${DEPLOYMENT_NAME}.gds-reliability.engineering",
          "team": "main",
          "username": "main",
          "password": "$(jq -r .main_team_password <infra/metadata)"
        }
      }
    }
    EOF
    echo "generating version config..."
    cat <<-EOF > concourse-provider-config/version.tfvars
      concourse_version = "$(cat concourse-release/version)"
      concourse_sha1 = "$(cat concourse-release/concourse-*-linux-amd64.tgz.sha1)"
    EOF
    cat concourse-provider-config/version.tfvars
    echo "writing main team password to file..."
    jq -r .main_team_password <infra/metadata > concourse-provider-config/main_team_password
    echo "OK!"
