platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/concourse-pipeline-resource
    tag: dev
  version:
    digest: sha256:cd899511e06c3027dc8429f4b38ba8ea32a4c0bea044f4711899d5987abf8fdf
inputs:
- name: tech-ops-private
outputs:
- name: deploy-info-pipelines-pipeline
params:
  DEPLOYMENT_NAME:
  FLY_USERNAME:
  FLY_PASSWORD:
run:
  path: /bin/bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    apk update && apk add jq
    mkdir -p deploy-info-pipelines-pipeline
    export PATH="$PATH:/opt/resource"
    fly -t concourse login -c "https://${DEPLOYMENT_NAME}.gds-reliability.engineering" -u $FLY_USERNAME -p $FLY_PASSWORD -n $FLY_USERNAME
    fly -t concourse sync
    fly -t concourse teams --json | jq '{
      "resources": [
        {
          "name": "tech-ops-private",
          "type": "git",
          "icon": "github-circle",
          "source": {
            "branch": ("((" + "deployment_branch" + "))"),
            "uri": "git@github.com:alphagov/tech-ops-private.git",
            "private_key": ("((" + "re-autom8-ci-github-ssh-private-key" + "))"),
            "paths": [
              "reliability-engineering/terraform/deployments/gds-tech-ops/cd/pipelines/info.yml"
            ]
          }
        }
      ],
      "jobs": [{
        "name": "deploy-info-pipelines",
        "serial": true,
        "plan": [
          {
            "get": "tech-ops-private",
            "trigger": true
          },
          {
            "in_parallel": [.[] | {
              "set_pipeline": "info",
              "team": .name,
              "file": "tech-ops-private/reliability-engineering/terraform/deployments/gds-tech-ops/cd/pipelines/info.yml",
              "vars": {
                "deployment": "'"${DEPLOYMENT_NAME}"'",
                "team": .name
                }
            }]
          }
        ]
      }]
    }' > deploy-info-pipelines-pipeline/deploy-info-pipelines.json
