{
 "title": "Alerts",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Links",
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "content": "---\n\n✈️ [Concourse](https://cd.gds-reliability.engineering)\n\n🔥 [Prometheus 1](https://prom-1.monitoring.cd.gds-reliability.engineering/graph)\n\n🔥 [Prometheus 2](https://prom-2.monitoring.cd.gds-reliability.engineering/graph)\n\n---"
  },
  {
   "title": "Number of running containers",
   "type": "graph",
   "description": "label_replace(node_uname_info, \"worker\", \"$1\", \"nodename\", \"(.*)\") * on (worker) group_left concourse_workers_containers",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "concourse_workers_containers and on(worker) label_replace(node_uname_info,\"worker\", \"$0\", \"nodename\",\".*\")",
     "legendFormat": "Number of containers - {{worker}} {{team}}"
    }
   ]
  },
  {
   "title": "Web CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"concourse_node_exporter\", role=\"concourse-web\",mode=\"idle\"}[5m])))",
     "legendFormat": "CPU usage - {{instance}}"
    }
   ]
  },
  {
   "title": "Web memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes {job=\"concourse_node_exporter\", role=\"concourse-web\"} / node_memory_MemTotal_bytes)",
     "legendFormat": "Memory usage - {{instance}}"
    }
   ]
  },
  { "title": "Firing alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 } },
  {
   "title": "Worker disk usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes {job=\"concourse_node_exporter\", role=\"concourse-worker\", mountpoint=\"/\"} / node_filesystem_size_bytes {job=\"concourse_node_exporter\", role=\"concourse-worker\", mountpoint=\"/\"})",
     "legendFormat": "Used disk space - {{instance}} - {{team}}"
    }
   ]
  },
  {
   "title": "Worker CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg without (cpu) (rate(node_cpu_seconds_total{job=\"concourse_node_exporter\", role=\"concourse-worker\",mode=\"idle\"}[5m])))",
     "legendFormat": "CPU usage - {{instance}} - {{team}}"
    }
   ]
  },
  {
   "title": "Worker memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes {job=\"concourse_node_exporter\", role=\"concourse-worker\"} / node_memory_MemTotal_bytes)",
     "legendFormat": "Memory usage - {{instance}} - {{team}}"
    }
   ]
  },
  {
   "title": "Number of containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(concourse_workers_containers)"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 } },
  {
   "title": "Prometheus scrapeability",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "absent(up{job=\"concourse_node_exporter\"})",
     "legendFormat": "All hosts reachable"
    }
   ]
  },
  {
   "title": "Prometheus disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes {job=\"concourse_node_exporter\", role=\"prometheus\", mountpoint=\"/var/lib/prometheus\"} / node_filesystem_size_bytes {job=\"concourse_node_exporter\", role=\"prometheus\", mountpoint=\"/var/lib/prometheus\"})",
     "legendFormat": "Used disk space - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_time_seconds{job=\"concourse_node_exporter\", role=\"concourse-worker\"})"
    }
   ]
  },
  {
   "title": "Number of web nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_time_seconds{job=\"concourse_node_exporter\", role=\"concourse-web\"})"
    }
   ]
  },
  {
   "title": "prom-1 Prometheus instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(up{job=\"concourse_node_exporter\",role=\"prometheus\"}==1)",
     "legendFormat": "Instance count"
    }
   ]
  },
  {
   "title": "prom-2 Prometheus instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(up{job=\"concourse_node_exporter\",role=\"prometheus\"}==1)",
     "legendFormat": "Instance count"
    }
   ]
  }
 ]
}