{
 "title": "Concourse",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Concourse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Statuses",
   "type": "graph",
   "description": "Shows the number of finished build over time with their statuses (succeeded, failed, aborted & errored).",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "succeeded",
     "expr": "sum(rate(concourse_builds_succeeded_total[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Succeeeded",
     "measurement": "build finished",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_status", "operator": "=", "value": "succeeded" }
     ]
    },
    {
     "alias": "errored",
     "expr": "sum(rate(concourse_builds_errored_total[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Errored",
     "measurement": "build finished",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_status", "operator": "=", "value": "errored" }
     ]
    },
    {
     "alias": "failed",
     "expr": "sum(rate(concourse_builds_failed_total[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Failed",
     "measurement": "build finished",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_status", "operator": "=", "value": "failed" }
     ]
    },
    {
     "alias": "aborted",
     "expr": "sum(rate(concourse_builds_aborted_total[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Aborted",
     "measurement": "build finished",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "build_status", "operator": "=", "value": "aborted" }
     ]
    }
   ]
  },
  {
   "title": "Total Builds (Finished-Started)",
   "type": "graph",
   "description": "Shows the number of builds started and finished over time.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(concourse_builds_finished_total[30m]))-sum(rate(concourse_builds_started_total[30m]))"
    }
   ]
  },
  {
   "title": "Worker State",
   "type": "graph",
   "description": "The status of Concourse Workers",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "expr": "max(concourse_workers_registered) by(state)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "legendFormat": "{{state}}",
     "measurement": "worker state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lidar Checks",
   "type": "graph",
   "description": "Shows the number of resource checks done per team.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(concourse_lidar_checks_finished_total{status=\"success\"}[$__interval]))",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Success",
     "measurement": "check finished",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(concourse_lidar_checks_finished_total{status=\"error\"}[$__interval]))",
     "legendFormat": "Error"
    }
   ]
  },
  { "title": "Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Average Web CPU",
   "type": "graph",
   "description": "Shows the average percentage of CPU usage in user space.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg(rate(node_cpu_seconds_total{job=\"concourse_node_exporter\", role=\"concourse-web\",mode=\"idle\"}[$__interval])))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "groupByTags": [ "host" ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\") * 100 FROM \"cpu\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=", "value": "web" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "description": "Shows the percentage of memory used (without counting cache) by the web instance.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"concourse_node_exporter\", role=\"concourse-web\"} / node_memory_MemTotal_bytes{job=\"concourse_node_exporter\", role=\"concourse-web\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "groupByTags": [ "host" ],
     "legendFormat": "{{instance}}",
     "measurement": "mem",
     "query": "SELECT mean(value) * 100 FROM \"memory\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=", "value": "web" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Rate",
   "type": "graph",
   "description": "Shows the transmission/receive rate of the web eth0 network interface.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "received {bosh-job: [[tag_bosh-job]], host: [[tag_host]]}",
     "expr": "avg(rate(node_network_receive_bytes_total{role=\"concourse-web\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "legendFormat": "Received",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" },
      { "condition": "AND", "key": "bosh-job", "operator": "=", "value": "web" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "sent {bosh-job: [[tag_bosh-job]], host: [[tag_host]]}",
     "expr": "avg(rate(node_network_transmit_bytes_total{role=\"concourse-web\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "legendFormat": "Sent",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" },
      { "condition": "AND", "key": "bosh-job", "operator": "=", "value": "web" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "graph",
   "description": "The number of queries that got created since the last time the metric was emitted.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(rate(concourse_db_queries_total[$__interval]))",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "database queries",
     "query": "SELECT non_negative_derivative(max(\"value\"), 10s) FROM \"database queries\" WHERE $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Number of Web Goroutines",
   "type": "graph",
   "description": "Shows the average number of the current running go routines for the web instances.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(go_goroutines{role=\"concourse-web\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "groupByTags": [ "host" ],
     "measurement": "goroutines",
     "query": "SELECT mean(\"value\") * 100 FROM \"cpu\" WHERE \"bosh-job\" = 'web' AND $timeFilter GROUP BY time($dynamic), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=", "value": "web" }
     ]
    }
   ]
  },
  {
   "title": "Web Open Files / Instance",
   "type": "graph",
   "description": "Shows the number of open files that belong to ATC.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{role=\"concourse-web\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Response Duration",
   "type": "graph",
   "description": "Shows the response time of every call per possible route.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by(route) (rate(concourse_http_responses_duration_seconds_count[$__interval]))",
     "fields": [
      { "func": "max", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" }
     ],
     "groupByTags": [ "route" ],
     "legendFormat": "{{route}}",
     "measurement": "http response time",
     "query": "SELECT mean(\"value\") FROM \"http response time\" WHERE $timeFilter GROUP BY time($interval), \"route\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Web Database Connections",
   "type": "graph",
   "description": "The number of open database connections per ATC node for both api and backend connection pools.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by(dbname) (concourse_db_connections)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ConnectionName" ], "type": "tag" }
     ],
     "legendFormat": "{{dbname}}",
     "measurement": "database connections",
     "query": "SELECT mean(\"value\") FROM \"scheduling: loading versions duration (ms)\" WHERE $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Average CPU / Team",
   "type": "graph",
   "description": "Average CPU per team using irate for better accuracy",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (team) (rate(node_cpu_seconds_total{role=\"concourse-worker\", mode=\"idle\", team!=\"main\"}[$__interval])))",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Available Memory / Team",
   "type": "graph",
   "description": "Shows the percentage of memory used (without counting cache) by team.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (team) (node_memory_MemAvailable_bytes {job=\"concourse_node_exporter\", role=\"concourse-worker\"} / node_memory_MemTotal_bytes)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "groupByTags": [ "host" ],
     "legendFormat": "{{team}}",
     "measurement": "mem",
     "query": "SELECT mean(value) * 100 FROM \"memory\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($dynamic), \"host\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=~", "value": "/.*worker.*/" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" }
     ]
    }
   ]
  },
  {
   "title": "Average Worker Network (Tx/Rx) / Team",
   "type": "graph",
   "description": "Shows the transmission/receive rate of the workers eth0 network interface.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Bytes received {bosh-job: [[tag_bosh-job]], host: [[tag_host]]}",
     "expr": "avg by (team) (rate(node_network_receive_bytes_total{role=\"concourse-worker\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "legendFormat": "Rx {{team}}",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" },
      { "condition": "AND", "key": "bosh-job", "operator": "=~", "value": "/.*worker.*/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Bytes received {bosh-job: [[tag_bosh-job]], host: [[tag_host]]}",
     "expr": "avg by (team) (rate(node_network_transmit_bytes_total{role=\"concourse-worker\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "legendFormat": "Tx {{team}}",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" },
      { "condition": "AND", "key": "bosh-job", "operator": "=~", "value": "/.*worker.*/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "No. of Worker Volumes / Team",
   "type": "graph",
   "description": "Shows the number of active volumes per team as reported by the baggageclaim server on the worker.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (team)(concourse_workers_volumes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" }
     ],
     "legendFormat": "{{team}}",
     "measurement": "worker volumes",
     "query": "SELECT mean(\"value\") FROM \"cpu\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($interval), \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total No. of Worker Containers",
   "type": "graph",
   "description": "Shows the number of active containers per team as reported by the garden server on the worker.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_worker",
     "expr": "sum by(team)(concourse_workers_containers)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" }
     ],
     "legendFormat": "{{team}}",
     "measurement": "worker containers",
     "query": "SELECT mean(\"value\") FROM \"worker containers\" WHERE \"bosh-deployment\" = 'concourse-wings' AND $timeFilter GROUP BY time($__interval), \"worker\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Available Disk / Team",
   "type": "graph",
   "description": "Displays the disk space available by Team",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (team)(node_filesystem_free_bytes{mountpoint=\"/\",role=\"concourse-worker\"} / node_filesystem_size_bytes)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "bosh-job" ], "type": "tag" }
     ],
     "legendFormat": "{{team}}",
     "measurement": "disk",
     "query": "SELECT mean(\"value\") * 100 FROM \"disk /var/vcap/data/baggageclaim/volumes\" WHERE \"bosh-job\" = 'worker' AND $timeFilter GROUP BY time($dynamic), \"tag\", \"host\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bosh-job", "operator": "=~", "value": "/.*worker.*/" },
      { "condition": "AND", "key": "bosh-deployment", "operator": "=~", "value": "/concourse-$deployment.*/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/var/vcap/data" }
     ]
    }
   ]
  },
  {
   "title": "No. of Open Files / Team",
   "type": "graph",
   "description": "The number of open file descriptors per team",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (team)(process_open_fds{role=\"concourse-worker\"})",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "No. of \"Up\" Workers / Team",
   "type": "graph",
   "description": "The number of \"up\" workers per team according to prometheus",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (team)(up{role=\"concourse-worker\"})",
     "legendFormat": "{{team}}"
    }
   ]
  }
 ]
}