{
 "title": "Service Level Objectives",
 "description": "service level objectives",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "availability",
     "expression": "1 - status5xx / (status5xx + status2xx)",
     "id": "errorRatio",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "content": "\n# Concourse Availability\n\nWe monitor the ratio of successful vs \nfailure HTTP status\ncodes from the load balancer that sits\nin front of the concourse-web nodes.\n\nThis is a good proxy for if the concourse\nUI/API is up and available for use.\n\n**We aim for 99.9% of requests to\nsucceed over a 7day period.**\n\n\n\n\n"
  },
  {
   "title": "Responsiveness",
   "type": "stat",
   "description": "Percentage of requests faster than 250ms",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(concourse_http_responses_duration_seconds_bucket{le=\"0.25\",status!=\"500\"}[5m]))\n/\nsum(rate(concourse_http_responses_duration_seconds_count[5m]))\n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "content": "\n# Concourse Responsiveness\n\nWe monitor the response times of calls\nto the Concourse API.\n\nHigh latency in these response times\ncan be an indicator that users are seeing\ndegraded performance in a number of areas\nsuch as sluggish UI, slow job triggering,\npoor build performance.\n\n**We aim for 99% of API requests to \nrespond within 250ms over a 7day period**\n\n\n"
  },
  {
   "title": "Activity",
   "type": "stat",
   "description": "Percentage of builds that did not error",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " 1 - sum(increase(concourse_builds_finished{status=\"errored\"}[5m])) / sum(increase(concourse_builds_finished[5m]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 16 },
   "content": "\n# Concourse Activity\n\nWe monitor the number of builds \n(job execute runs) that get\nprocessed without erroring.\n\nWhile there are several cases where\nerrored (orange) builds can be caused\nby users themselves, it is common that\nthese error states are caused by problems\nsuch as worker-nodes disappearing, \ncontainers being unable to get scheduled\nand configuration issues that cannot\nbe resolved by the user.\n\n**We aim for 99.9% of builds \nto be successfully processed\nwithin a 7day period.**\n\n\n\n"
  }
 ]
}