{
 "title": "Concourse internal",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "query": "concourse_builds_duration_seconds_bucket"
   },
   {
    "name": "pipeline",
    "query": "concourse_builds_duration_seconds_bucket { team=~\"$team\" }"
   },
   {
    "name": "exported_job",
    "query": "concourse_builds_duration_seconds_bucket { pipeline=~\"$pipeline\", team=~\"$team\" }"
   }
  ]
 },
 "panels": [
  {
   "title": "Build durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(concourse_builds_duration_seconds_bucket { exported_job=~\"$exported_job\", pipeline=~\"$pipeline\", team=~\"$team\" }[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Jobs scheduling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_jobs_scheduling {}" }
   ]
  },
  {
   "title": "Locks held",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_locks_held {}" }
   ]
  },
  {
   "title": "Builds running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_builds_running" }
   ]
  },
  {
   "title": "Tasks waiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_tasks_waiting" }
   ]
  }
 ]
}