{
 "title": "Metrics by team",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Team", "query": "label_values(node_cpu, team)" }
  ]
 },
 "panels": [
  {
   "title": "Links",
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "content": "---\n\n✈️ [Concourse](https://cd.gds-reliability.engineering)\n\n🔥 [Prometheus 1](https://prom-1.monitoring.cd.gds-reliability.engineering/graph)\n\n🔥 [Prometheus 2](https://prom-2.monitoring.cd.gds-reliability.engineering/graph)\n\n---"
  },
  {
   "title": "Number of running containers",
   "type": "graph",
   "description": "label_replace(node_uname_info, \"worker\", \"$1\", \"nodename\", \"(.*)\") * on (worker) group_left concourse_workers_containers",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "concourse_workers_containers * on(worker) group_left(team) label_replace(node_uname_info{team=\"$Team\"},\"worker\", \"$0\", \"nodename\",\".*\")",
     "legendFormat": "Number of containers - {{instance}}"
    }
   ]
  },
  {
   "title": "Worker CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg without (cpu) (rate(node_cpu{team=\"$Team\",job=\"concourse_node_exporter\", role=\"concourse-worker\",mode=\"idle\"}[5m])))",
     "legendFormat": "CPU usage - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(concourse_workers_containers * on(worker) group_left(team) label_replace(node_uname_info{team=\"$Team\"},\"worker\", \"$0\", \"nodename\",\".*\"))"
    }
   ]
  },
  {
   "title": "Worker disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail {job=\"concourse_node_exporter\", role=\"concourse-worker\", mountpoint=\"/\",team=\"$Team\"} / node_filesystem_size {job=\"concourse_node_exporter\", role=\"concourse-worker\", mountpoint=\"/\"})",
     "legendFormat": "Used disk space - {{instance}}"
    }
   ]
  },
  {
   "title": "Worker memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable {team=\"$Team\",job=\"concourse_node_exporter\", role=\"concourse-worker\"} / node_memory_MemTotal)",
     "legendFormat": "Memory usage - {{instance}} - {{team}}"
    }
   ]
  },
  {
   "title": "Number of worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_time{job=\"concourse_node_exporter\", role=\"concourse-worker\",team=\"$Team\"})"
    }
   ]
  },
  {
   "title": "Number of web nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_time{job=\"concourse_node_exporter\", role=\"concourse-web\"})"
    }
   ]
  }
 ]
}