name: govsvc concourse-task-toolbox

on:
  push:
    branches:
      - 'master'
    paths:
      - 'reliability-engineering/dockerfiles/govsvc/oncourse-task-toolbox/**'

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag used within docker repository to mark as unique"
        required: false
        type: string

jobs:
  build-and-push:
    uses: alphagov/tech-ops/.github/workflows/publish_to_docker.yml@master
    with:
      docker_context: ./reliability-engineering/dockerfiles/govsvc/concourse-task-toolbox
      push_to_ghcr: true
      push_to_dockerhub: false
      ghcr_repo: ghcr.io/alphagov/automate/task-toolbox
      image_tag: ${{ github.event.inputs.image_tag }}
    secrets:
      ghcr_username: ${{ secrets.GHCR_USERNAME }}
      ghcr_token: ${{ secrets.CHCR_TOKEN }}
